/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.client;

//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

import com.mycompany.client.models.Etudiant;
import com.mycompany.client.models.Matiere;
import com.mycompany.client.models.Note;

//import com.mycompany.client.mocks.MockData;
import com.mycompany.client.utils.ApiClient;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;

import com.formdev.flatlaf.FlatLightLaf;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author senketsu
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private List<Etudiant> tousLesEtudiants;
    private List<Etudiant> etudiantsFiltres;
    private List<Matiere> toutesLesMatieres;
    private List<Note> toutesLesNotes;
    
    // Flag pour eviter les appel multiple
    private boolean isInitialized  = false;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
           UIManager.setLookAndFeel(new FlatLightLaf()); 
        } catch (UnsupportedLookAndFeelException e) {
            System.err.println("Erreur chargement FlatLaf: " + e.getMessage());
            
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            }
        }
        
                
        // 2. Initialiser les listes à VIDE pour éviter les NullPointerException
        tousLesEtudiants = new ArrayList<>();
        toutesLesMatieres = new ArrayList<>();
        toutesLesNotes = new ArrayList<>();
        etudiantsFiltres = new ArrayList<>();
        
        initComponents();
        
        // NETTOYER LES COMBOBOX (enlève les items par défaut)
        nettoyerCombobox();
        
        // Charger les donnees depuis l'API
        chargerDonneesInitiales();
        
//        remplirToutesLesCombobox(); // emplir les listes deroulantes
//        rafraichirTousLesAffichages(); // Afficher les donnees dans les tableaux
        configurerFenetre();
        
        // Charger les données depuis l'API (dans un thread séparé pour ne pas bloquer l'UI)
        chargerDonneesEnArrierePlan();
        
        // Verification connexion au Backend 
        verifierConnexionBackend();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlEtudiants = new javax.swing.JPanel();
        pnlRecherche = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtRecherche = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        btnResetRecherche = new javax.swing.JButton();
        cmbFiltreNiveau = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEtudiants = new javax.swing.JTable();
        pnlBoutons = new javax.swing.JPanel();
        btnAjouterEtudiant = new javax.swing.JButton();
        btnModifierEtudiant = new javax.swing.JButton();
        btnSupprimerEtudiant = new javax.swing.JButton();
        pnlMatieres = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatieres = new javax.swing.JTable();
        pnlBoutonsMatieres = new javax.swing.JPanel();
        btnAjouterMatiere = new javax.swing.JButton();
        btnModifierMatiere = new javax.swing.JButton();
        btnSupprimerMatiere = new javax.swing.JButton();
        pnlNotes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNotes = new javax.swing.JTable();
        pnlFiltreNotes = new javax.swing.JPanel();
        cmbFiltreNotesEtudiant = new javax.swing.JComboBox<>();
        btnFiltrerNotes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        btnAjouterNote = new javax.swing.JButton();
        btnModifierNote = new javax.swing.JButton();
        btnSupprimerNote = new javax.swing.JButton();
        pnlBulletin = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBulletin = new javax.swing.JTable();
        cmbEtudiant = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMoyenne = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblObservation = new javax.swing.JLabel();
        pnlClassement = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblClassement = new javax.swing.JTable();
        cmbNiveauClassement = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRecherche.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel5.setText("Rechercher :");
        jLabel5.setPreferredSize(new java.awt.Dimension(64, 28));
        pnlRecherche.add(jLabel5);

        txtRecherche.setPreferredSize(new java.awt.Dimension(170, 28));
        pnlRecherche.add(txtRecherche);

        btnRechercher.setText("Rechercher");
        btnRechercher.setPreferredSize(new java.awt.Dimension(100, 28));
        btnRechercher.addActionListener(this::btnRechercherActionPerformed);
        pnlRecherche.add(btnRechercher);

        btnResetRecherche.setText("Réinitialiser");
        btnResetRecherche.setPreferredSize(new java.awt.Dimension(100, 28));
        btnResetRecherche.addActionListener(this::btnResetRechercheActionPerformed);
        pnlRecherche.add(btnResetRecherche);

        cmbFiltreNiveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFiltreNiveau.setPreferredSize(new java.awt.Dimension(120, 30));
        cmbFiltreNiveau.addActionListener(this::cmbFiltreNiveauActionPerformed);
        pnlRecherche.add(cmbFiltreNiveau);

        tblEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEtudiants);

        pnlBoutons.setPreferredSize(new java.awt.Dimension(275, 50));

        btnAjouterEtudiant.setText("Ajouter");
        btnAjouterEtudiant.addActionListener(this::btnAjouterEtudiantActionPerformed);

        btnModifierEtudiant.setText("Modifier");
        btnModifierEtudiant.addActionListener(this::btnModifierEtudiantActionPerformed);

        btnSupprimerEtudiant.setText("Supprimer");
        btnSupprimerEtudiant.addActionListener(this::btnSupprimerEtudiantActionPerformed);

        javax.swing.GroupLayout pnlBoutonsLayout = new javax.swing.GroupLayout(pnlBoutons);
        pnlBoutons.setLayout(pnlBoutonsLayout);
        pnlBoutonsLayout.setHorizontalGroup(
            pnlBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoutonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouterEtudiant)
                .addGap(18, 18, 18)
                .addComponent(btnModifierEtudiant)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimerEtudiant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBoutonsLayout.setVerticalGroup(
            pnlBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoutonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBoutonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouterEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnModifierEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupprimerEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlEtudiantsLayout = new javax.swing.GroupLayout(pnlEtudiants);
        pnlEtudiants.setLayout(pnlEtudiantsLayout);
        pnlEtudiantsLayout.setHorizontalGroup(
            pnlEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEtudiantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addComponent(pnlRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBoutons, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlEtudiantsLayout.setVerticalGroup(
            pnlEtudiantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEtudiantsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBoutons, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Étudiants", pnlEtudiants);

        tblMatieres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMatieres);

        pnlBoutonsMatieres.setPreferredSize(new java.awt.Dimension(275, 50));

        btnAjouterMatiere.setText("Ajouter");
        btnAjouterMatiere.setMaximumSize(new java.awt.Dimension(72, 28));
        btnAjouterMatiere.setMinimumSize(new java.awt.Dimension(72, 28));
        btnAjouterMatiere.setPreferredSize(new java.awt.Dimension(72, 28));
        btnAjouterMatiere.addActionListener(this::btnAjouterMatiereActionPerformed);

        btnModifierMatiere.setText("Modifier");
        btnModifierMatiere.addActionListener(this::btnModifierMatiereActionPerformed);

        btnSupprimerMatiere.setText("Supprimer");
        btnSupprimerMatiere.addActionListener(this::btnSupprimerMatiereActionPerformed);

        javax.swing.GroupLayout pnlBoutonsMatieresLayout = new javax.swing.GroupLayout(pnlBoutonsMatieres);
        pnlBoutonsMatieres.setLayout(pnlBoutonsMatieresLayout);
        pnlBoutonsMatieresLayout.setHorizontalGroup(
            pnlBoutonsMatieresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoutonsMatieresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouterMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifierMatiere)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimerMatiere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBoutonsMatieresLayout.setVerticalGroup(
            pnlBoutonsMatieresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoutonsMatieresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBoutonsMatieresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifierMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimerMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMatieresLayout = new javax.swing.GroupLayout(pnlMatieres);
        pnlMatieres.setLayout(pnlMatieresLayout);
        pnlMatieresLayout.setHorizontalGroup(
            pnlMatieresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMatieresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMatieresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMatieresLayout.createSequentialGroup()
                        .addComponent(pnlBoutonsMatieres, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)))
        );
        pnlMatieresLayout.setVerticalGroup(
            pnlMatieresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMatieresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBoutonsMatieres, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("Matières", pnlMatieres);

        jScrollPane3.setViewportView(tblNotes);

        btnFiltrerNotes.setText("Afficher");
        btnFiltrerNotes.addActionListener(this::btnFiltrerNotesActionPerformed);

        jLabel6.setText("Filtrer par étudiant :");

        javax.swing.GroupLayout pnlFiltreNotesLayout = new javax.swing.GroupLayout(pnlFiltreNotes);
        pnlFiltreNotes.setLayout(pnlFiltreNotesLayout);
        pnlFiltreNotesLayout.setHorizontalGroup(
            pnlFiltreNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltreNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbFiltreNotesEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        pnlFiltreNotesLayout.setVerticalGroup(
            pnlFiltreNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltreNotesLayout.createSequentialGroup()
                .addGroup(pnlFiltreNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrerNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbFiltreNotesEtudiant))
                .addContainerGap())
            .addGroup(pnlFiltreNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnAjouterNote.setText("Ajouter");
        btnAjouterNote.setPreferredSize(new java.awt.Dimension(72, 25));
        btnAjouterNote.addActionListener(this::btnAjouterNoteActionPerformed);

        btnModifierNote.setText("Modifier");
        btnModifierNote.setPreferredSize(new java.awt.Dimension(76, 25));
        btnModifierNote.addActionListener(this::btnModifierNoteActionPerformed);

        btnSupprimerNote.setText("Supprimer");
        btnSupprimerNote.setPreferredSize(new java.awt.Dimension(85, 25));
        btnSupprimerNote.addActionListener(this::btnSupprimerNoteActionPerformed);

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouterNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifierNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimerNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterNote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifierNote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimerNote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlNotesLayout = new javax.swing.GroupLayout(pnlNotes);
        pnlNotes.setLayout(pnlNotesLayout);
        pnlNotesLayout.setHorizontalGroup(
            pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addComponent(pnlFiltreNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNotesLayout.setVerticalGroup(
            pnlNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFiltreNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Notes", pnlNotes);

        tblBulletin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblBulletin);

        cmbEtudiant.addActionListener(this::cmbEtudiantActionPerformed);

        jLabel1.setText("Choisir étudiant :");

        jLabel2.setText("Moyenne :");

        jLabel3.setText("Observation :");

        javax.swing.GroupLayout pnlBulletinLayout = new javax.swing.GroupLayout(pnlBulletin);
        pnlBulletin.setLayout(pnlBulletinLayout);
        pnlBulletinLayout.setHorizontalGroup(
            pnlBulletinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlBulletinLayout.createSequentialGroup()
                .addGroup(pnlBulletinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBulletinLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBulletinLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblObservation, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBulletinLayout.setVerticalGroup(
            pnlBulletinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBulletinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBulletinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBulletinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObservation))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Bulletin", pnlBulletin);

        tblClassement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblClassement);

        cmbNiveauClassement.addActionListener(this::cmbNiveauClassementActionPerformed);

        jLabel4.setText("Niveau :");

        javax.swing.GroupLayout pnlClassementLayout = new javax.swing.GroupLayout(pnlClassement);
        pnlClassement.setLayout(pnlClassementLayout);
        pnlClassementLayout.setHorizontalGroup(
            pnlClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(pnlClassementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNiveauClassement, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClassementLayout.setVerticalGroup(
            pnlClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClassementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNiveauClassement, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Classement", pnlClassement);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Action pour ajouter une note (boîte de dialogue simple pour l'instant)
    */
    private void btnAjouterNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterNoteActionPerformed
        // Juste affichage boite de dialogue 
        ajouterNote();
    }//GEN-LAST:event_btnAjouterNoteActionPerformed

    private void btnModifierNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierNoteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNotes.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez d'abord sélectionner une note dans le tableau.",
                "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        modifierNote();
    }//GEN-LAST:event_btnModifierNoteActionPerformed

    private void btnSupprimerNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerNoteActionPerformed
        int selectedRow = tblNotes.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,"Veuillez d'abord sélectionner une note dans le tableau.",
                "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        supprimerNote();
    }//GEN-LAST:event_btnSupprimerNoteActionPerformed

    /**
    * Action quand on change d'étudiant dans la combo box
    */
    private void cmbEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEtudiantActionPerformed
       afficherBulletin();
    }//GEN-LAST:event_cmbEtudiantActionPerformed

    private void cmbNiveauClassementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNiveauClassementActionPerformed
        afficherClassement();
    }//GEN-LAST:event_cmbNiveauClassementActionPerformed

    private void btnAjouterEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterEtudiantActionPerformed
        ajouterEtudiant();
    }//GEN-LAST:event_btnAjouterEtudiantActionPerformed

    private void btnModifierEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierEtudiantActionPerformed
        modifierEtudiant();
    }//GEN-LAST:event_btnModifierEtudiantActionPerformed

    private void btnSupprimerEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerEtudiantActionPerformed
        supprimerEtudiant();
    }//GEN-LAST:event_btnSupprimerEtudiantActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        afficherEtudiantsFiltres();
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnResetRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRechercheActionPerformed
        txtRecherche.setText(""); afficherEtudiantsFiltres();
    }//GEN-LAST:event_btnResetRechercheActionPerformed

    private void cmbFiltreNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltreNiveauActionPerformed
            // Vérifier que la combo n'est pas null
        if (cmbFiltreNiveau != null) {
            afficherEtudiantsFiltres();
        }
    }//GEN-LAST:event_cmbFiltreNiveauActionPerformed

    private void btnAjouterMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterMatiereActionPerformed
        ajouterMatiere();
    }//GEN-LAST:event_btnAjouterMatiereActionPerformed

    private void btnModifierMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierMatiereActionPerformed
        modifierMatiere();
    }//GEN-LAST:event_btnModifierMatiereActionPerformed

    private void btnSupprimerMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerMatiereActionPerformed
        supprimerMatiere();
    }//GEN-LAST:event_btnSupprimerMatiereActionPerformed

    private void btnFiltrerNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrerNotesActionPerformed
       try {
            afficherNotesFiltrees();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnFiltrerNotesActionPerformed
   
    /**
     * Nettoie les JComboBox en supprimant les items par defaut
     */
    private void nettoyerCombobox() {
        cmbFiltreNiveau.removeAllItems();
        cmbEtudiant.removeAllItems();
        cmbNiveauClassement.removeAllItems();
        cmbFiltreNotesEtudiant.removeAllItems();
    }
    
    /**
     * Charger les donnees initaile depuis le Backend 
     */
    private void chargerDonneesInitiales() {
        try {
            tousLesEtudiants = ApiClient.getEtudiants();
            toutesLesMatieres = ApiClient.getMatieres();
            toutesLesNotes = ApiClient.getNotes();
            etudiantsFiltres = new ArrayList<>(tousLesEtudiants);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Erreur de chargement des donnees: " + e.getMessage() + "\n" + 
                    "Vérifiez que le backend est démarré", 
                    "Erreur de connexion",
                    JOptionPane.ERROR_MESSAGE);
            // Initialiser avec des listes vides pour eviter NullPOinterException
            tousLesEtudiants = new ArrayList<>();
            toutesLesMatieres = new ArrayList<>();
            toutesLesNotes = new ArrayList<>();
            etudiantsFiltres = new ArrayList<>();
        }
    }
    
    /**
     * 
     */
    private void configurerFenetre() {
         // Design
        setSize(980, 540);
        setTitle("Gestion des Notes - Projet Swing");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        getContentPane().setBackground(new java.awt.Color(245, 245, 250));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    }
    
    /**
     * Charge les données en arrière-plan pour ne pas bloquer l'interface
     */
    private void chargerDonneesEnArrierePlan() {
        new Thread(() -> {
            try {
                // Charger les données depuis l'API
                tousLesEtudiants = ApiClient.getEtudiants();
                toutesLesMatieres = ApiClient.getMatieres();
                toutesLesNotes = ApiClient.getNotes();
                etudiantsFiltres = new ArrayList<>(tousLesEtudiants);
                
                // Mettre à jour l'interface dans le thread Swing
                SwingUtilities.invokeLater(() -> {
                    remplirToutesLesCombobox();
                    rafraichirTousLesAffichages();
                    isInitialized = true;
                });
            } catch (Exception e) {
                System.err.println("Erreur chargement données: " + e.getMessage());
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, 
                        "Erreur de chargement des données: " + e.getMessage() + "\n" +
                        "Vérifiez que le backend est démarré (npm run dev dans le dossier server)",
                        "Erreur de connexion", 
                        JOptionPane.ERROR_MESSAGE);
                    // Afficher des données vides
                    afficherEtudiantsVides();
                    isInitialized = true;
                });
            }
        }).start();
    }
    
        /**
     * Remplir toutes les JComboBo avec les donnees charges
     */
    private void remplirToutesLesCombobox() {
        // Filtre niveau pour l'onglet etudiants
        cmbFiltreNiveau.removeAllItems();
        cmbFiltreNiveau.addItem("Tous");
        cmbFiltreNiveau.addItem("L1");
        cmbFiltreNiveau.addItem("L2");
        cmbFiltreNiveau.addItem("L3");
        cmbFiltreNiveau.addItem("M1");
        cmbFiltreNiveau.addItem("M2");
        
        // Selectionner etudiant pour le bulletin
        if (cmbEtudiant != null) {
            cmbEtudiant.removeAllItems();
            for (Etudiant e : tousLesEtudiants) {
                cmbEtudiant.addItem(e.getNe() + " - " + e.getNom());
            }
        }
        
        // Niveau pour le classement 
        if (cmbNiveauClassement != null) {
            cmbNiveauClassement.removeAllItems();
            cmbNiveauClassement.addItem("L1");
            cmbNiveauClassement.addItem("L2");
            cmbNiveauClassement.addItem("L3");
            cmbNiveauClassement.addItem("M1");
            cmbNiveauClassement.addItem("M2");
        }
        
        // Filtre etudiant pour l'onglet notes
        cmbFiltreNotesEtudiant.removeAllItems();
        cmbFiltreNotesEtudiant.addItem("Tous les étudiants");
        for (Etudiant e : tousLesEtudiants) {
            cmbFiltreNotesEtudiant.addItem(e.getNe() + " - " + e.getNom());
        }
    }
    
    /**
     * Rafraichir tous les affichages : tableau, bulletins, classements
     */
    private void rafraichirTousLesAffichages() {
        afficherEtudiantsFiltres();
        afficherMatieres();
        afficherNotesFiltrees();
        afficherBulletin();
        afficherClassement();
    }
    
    /**
     * Verifier si le backend est accessible 
     */
    private void verifierConnexionBackend() {
        new Thread(() -> {
            boolean connecte = ApiClient.testConnexion();
            
            if (!connecte) {
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, 
                        "Le Backend n'est pas accessible" ,
                        "Connexion au serveur ...",
                        JOptionPane.WARNING_MESSAGE);
                
                });
            }
        }).start();
    }
    /**
    * Méthode principale d'affichage des étudiants (avec filtre et recherche)
    */ 
    private void afficherEtudiantsFiltres() {
        // Vérifier que tousLesEtudiants n'est pas null
//        if (tousLesEtudiants == null) {
//            try {
//                tousLesEtudiants = ApiClient.getEtudiants();
////            etudiantsFiltres = new ArrayList<>(tousLesEtudiants);
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage());
//            }
//        }
    
        String recherche = txtRecherche.getText().toLowerCase();
//        String niveauFiltre = (String) cmbFiltreNiveau.getSelectedItem();
           
        String niveauFiltre = "Tous";
        if (cmbFiltreNiveau != null && cmbFiltreNiveau.getSelectedItem() != null) {
            niveauFiltre = (String) cmbFiltreNiveau.getSelectedItem();
        }

        final String niveauFiltreFinal = niveauFiltre;
    
        // Filtrer les etudiants
        etudiantsFiltres = tousLesEtudiants.stream()
                .filter(e -> {
                    // Filtre par recherche (ne oou nom)
                    boolean matchRecherche = recherche.isEmpty() ||
                            e.getNe().toLowerCase().contains(recherche) ||
                            e.getNom().toLowerCase().contains(recherche);
                    
                    // Filtrer par niveau 
                    boolean matchNiveau = niveauFiltreFinal.equals("Tous") ||
                            e.getNiveau().equals(niveauFiltreFinal);
                    
                    return matchRecherche && matchNiveau;
                })
                .collect(Collectors.toList());
        
        // Afficher dans la table
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"N° Étudiant", "Nom", "Niveau"}, 0
        );
        
        for (Etudiant e : etudiantsFiltres) {
            model.addRow(new Object[]{e.getNe(), e.getNom(), e.getNiveau()});
        }
        
        tblEtudiants.setModel(model);
//        centrerColonnesTable(tblEtudiants);
        tblEtudiants.setRowHeight(28);
    }
    
        /**
     * Affiche un tableau vide (cas d'erreur)
     */
    private void afficherEtudiantsVides() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"N° Étudiant", "Nom", "Niveau"}, 0);
        tblEtudiants.setModel(model);
    }
    
        private void afficherNotesFiltrees() {
//        if (toutesLesNotes == null) {
//            toutesLesNotes = ApiClient.getNotes();
//        }
            
        List<Note> notesAfficher = toutesLesNotes;
        
        // Filtrer les etudiants si selectionnee
        if (cmbFiltreNotesEtudiant != null && cmbFiltreNotesEtudiant.getSelectedIndex() > 0) {
            Object selected = cmbFiltreNotesEtudiant.getSelectedItem();
            if (selected != null && !selected.equals("Tous les étudiants")) {
                String selectedStr = selected.toString();
                String ne = selectedStr.split(" - ")[0];
                notesAfficher = toutesLesNotes.stream()
                    .filter(n -> n.getNe().equals(ne))
                    .collect(Collectors.toList());
            }
        }

//        List<Etudiant> etudiants = ApiClient.getEtudiants();
//        List<Matiere> matieres = ApiClient.getMatieres();

        DefaultTableModel model = new DefaultTableModel(
            new String[]{"N° Étudiant", "Étudiant", "Matière", "Note"}, 0
        );

        for (Note note : notesAfficher) {
            String nomEtudiant = tousLesEtudiants.stream()
                .filter(e -> e.getNe().equals(note.getNe()))
                .findFirst()
                .map(Etudiant::getNom)
                .orElse("Inconnu");

            String libelleMatiere = toutesLesMatieres.stream()
                .filter(m -> m.getCodemat().equals(note.getCodemat()))
                .findFirst()
                .map(Matiere::getLibelle)
                .orElse("Inconnu");

            model.addRow(new Object[]{
                note.getNe(),
                nomEtudiant,
                libelleMatiere,
                note.getNote()
            });
        }

        tblNotes.setModel(model);
//        centrerColonnesTable(tblNotes);
        tblNotes.setRowHeight(30);
    }
 
    /**
    * Calcule et affiche le bulletin de l'étudiant sélectionné
    */
    private void afficherBulletin() {
        if (cmbEtudiant == null || cmbEtudiant.getItemCount() == 0) {
            afficherBulletinVide();
            return;
        }
        
        // Recuperer Etudiant selectionne
        Object selectedObj = cmbEtudiant.getSelectedItem();
        if (selectedObj == null) {
            afficherBulletinVide();
            return;
        }

        String selected = selectedObj.toString();
        
        String ne = selected.split(" - ")[0];    
        
        System.out.println("Demande bulletin pour: " + ne);

        try {
            // Appeler l'API pour recuperer le buletin pre-calcule
            JsonObject bulletin = ApiClient.getBulletin(ne);
            
            // Verifier que le bulletin n'est pas null
            if (bulletin == null) {
                afficherBulletinVide();
                JOptionPane.showMessageDialog(this, "Aucun bulletin pour cet étudiant",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            System.out.println("Bulletin reçu: " + bulletin.toString());
            
            // Veifier que les notes existe
            JsonElement notesElement = bulletin.get("notes");
            if (notesElement == null || notesElement.isJsonNull()) {
                System.err.println("Notes null pour: " + ne);
                afficherBulletinVide();
                JOptionPane.showMessageDialog(this, 
                    "Aucune note trouvée pour l'étudiant " + ne,
                    "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
//            var notes = bulletin.getAsJsonArray("notes");
            JsonArray notes = notesElement.getAsJsonArray();
            if (notes.size() == 0) {
                System.err.println("Notes vides pour: " + ne);
                afficherBulletinVide();
                JOptionPane.showMessageDialog(this, 
                    "Aucune note enregistrée pour l'étudiant " + ne,
                    "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        
            // CReer tableau des bulletins
            DefaultTableModel model = new DefaultTableModel(
               new String[]{"Matière", "Coefficient", "Note", "Note Pondérée"}, 0
            );

            double sommePonderee = 0;
            int sommeCoef = 0;

            for (JsonElement element : notes) {
                JsonObject note = element.getAsJsonObject();
                String libelle = note.get("libelle").getAsString();
                int coef = note.get("coef").getAsInt();

                double valeur = note.get("note").getAsDouble();
                double ponderee = note.get("note_ponderee").getAsDouble();
           
                sommePonderee += ponderee;
                sommeCoef += coef;
                
                model.addRow(new Object[]{
                    libelle,
                    coef,
                    valeur,
                    String.format("%.2f", ponderee)
                });
            }
        
            // Calculer la moyenne
            double moyenne = 0;
            JsonElement moyenneElement = bulletin.get("moyenne");
            
            if (moyenneElement != null && !moyenneElement.isJsonNull()) {
                moyenne = moyenneElement.getAsDouble();
            } else {
                // Calculer la moyenne localement si le backend ne la fournit pas
                moyenne = sommeCoef > 0 ? sommePonderee / sommeCoef : 0;
            }
            
            String observation = "ÉCHEC";
            JsonElement obsElement = bulletin.get("observation");
            if (obsElement != null && !obsElement.isJsonNull()) {
                observation = obsElement.getAsString();
            } else {
                observation = moyenne >= 10 ? "ADMIS" : (moyenne >= 7.5 ? "REDOUBLANT" : "ÉCHEC");
            }

            // Afficher la moyenne et l'obs
            tblBulletin.setModel(model);
            lblMoyenne.setText(String.format("%.2f", moyenne));
            lblObservation.setText(observation);

            // Appliquer une couleur a l'observation
            if (observation.equals("ADMIS")) {
                lblObservation.setForeground(new java.awt.Color(0, 150, 0)); // Vert
            } else if (observation.equals("REDOUBLANT")) {
                lblObservation.setForeground(new java.awt.Color(255, 165, 0)); // Orange
            } else {
                lblObservation.setForeground(java.awt.Color.RED); // Rouge
            }

    //        tblBulletin.setModel(model);
            tblBulletin.setRowHeight(30);
        } catch (Exception e) {
            System.err.println("Erreur bulletin: " + e.getMessage());            
            afficherBulletinVide();
            
            // Afficher Message plus claire
            if (e.getMessage().contains("404")) {
                JOptionPane.showMessageDialog(this, """
                                                    Bulletin non trouv\u00e9 pour cet \u00e9tudiant.
                                                    V\u00e9rifiez que l'\u00e9tudiant a des notes.""", 
                "Information", JOptionPane.INFORMATION_MESSAGE);
            }
//            JOptionPane.showMessageDialog(this,
//                    "Erreur chargement bulletin: " + e.getMessage(),
//                    "Erreur", JOptionPane.ERROR_MESSAGE);
//            afficherBulletinVide();
        }
    }
    
    /**
     * Affiche un bulletin vide
     */
    private void afficherBulletinVide() {        
        // Afficher un message vide
        DefaultTableModel emptyModel = new DefaultTableModel(
            new String[]{"Matière", "Coefficient", "Note", "Note Pondérée"}, 0);
        tblBulletin.setModel(emptyModel);
        lblMoyenne.setText("0.00");
        lblObservation.setText("Aucun étudiant");
    }

    /**
 * Affiche le classement pour le niveau sélectionné
 */
    private void afficherClassement() {
        if (cmbNiveauClassement == null || cmbNiveauClassement.getItemCount() == 0) {
            DefaultTableModel emptyModel = new DefaultTableModel(
                new String[]{"N° Étudiant", "Nom", "Moyenne"}, 0);
            tblClassement.setModel(emptyModel);
            return;
        }

        Object selectedObj = cmbNiveauClassement.getSelectedItem();
        if (selectedObj == null) return;

        String niveau = selectedObj.toString();
        
        try {
            // Appeler API pour recuperer le classement pre-calcule
            var classement = ApiClient.getClassement(niveau);
            
            if (classement == null || classement.size() == 0) {
                DefaultTableModel emptyModel = new DefaultTableModel(
                new String[]{"N° Étudiant", "Nom", "Moyenne"}, 0);
                tblClassement.setModel(emptyModel);
                JOptionPane.showMessageDialog(this, 
                    "Aucun étudiant trouvé pour le niveau " + niveau,
                    "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // Créer le tableau
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"N° Étudiant", "Nom", "Moyenne"}, 0
            );
            
            for (var element : classement) {
                var obj = element.getAsJsonObject();
                String ne = obj.get("ne").getAsString();
                String nom = obj.get("nom").getAsString();
                double moyenne = obj.get("moyenne").getAsDouble();
                model.addRow(new Object[]{ne, nom, String.format("%.2f", moyenne)});
            }
            
            tblClassement.setModel(model);
    //      centrerColonnesTable(tblClassement);
            tblClassement.setRowHeight(30);
        } catch (Exception e) {
            System.err.println("Erreur classement: " + e.getMessage());
            
            if (e.getMessage().contains("404")) {
                DefaultTableModel emptyModel = new DefaultTableModel(
                new String[]{"N° Étudiant", "Nom", "Moyenne"}, 0);
                tblClassement.setModel(emptyModel);
                JOptionPane.showMessageDialog(this, 
                    "Aucun étudiant trouvé pour le niveau " + niveau,
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    
    /**
    * Ajouter un étudiant (dialogue personnalisé)
    */
    private void ajouterEtudiant() {
     // Créer un dialogue personnalisé
        JDialog dialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), " Ajouter un étudiant", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(400, 250);
        dialog.setLocationRelativeTo(this);

        // Panel du formulaire
        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        formPanel.add(new JLabel("N° Étudiant :"));
        JTextField txtNe = new JTextField();
        formPanel.add(txtNe);

        formPanel.add(new JLabel("Nom :"));
        JTextField txtNom = new JTextField();
        formPanel.add(txtNom);

        formPanel.add(new JLabel("Niveau :"));
        JComboBox<String> cmbNiveau = new JComboBox<>(new String[]{"L1", "L2", "L3", "M1", "M2"});
        formPanel.add(cmbNiveau);

        // Panel des boutons
        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnOk = new JButton("Enregistrer");
        JButton btnAnnuler = new JButton("Annuler");
        buttonPanel.add(btnOk);
        buttonPanel.add(btnAnnuler);

        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        // Action du bouton OK
        btnOk.addActionListener(e -> {
            String ne = txtNe.getText().trim();
            String nom = txtNom.getText().trim();
            String niveau = (String) cmbNiveau.getSelectedItem();

            if (ne.isEmpty() || nom.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Veuillez remplir tous les champs !", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Vérifier si l'étudiant existe déjà
            boolean existe = tousLesEtudiants.stream().anyMatch(et -> et.getNe().equals(ne));
            if (existe) {
                JOptionPane.showMessageDialog(dialog, "Ce numéro d'étudiant existe déjà !", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ajouter l'étudiant
            new Thread (() -> {
                
                try {
                    Etudiant nouvelEtudiant = new Etudiant(ne, nom, niveau);
    //                tousLesEtudiants.add(nouvelEtudiant);
                    if (ApiClient.ajouterEtudiant(nouvelEtudiant)) {

                        // echarger toutes les donnees
                        tousLesEtudiants = ApiClient.getEtudiants();
                        etudiantsFiltres = new ArrayList<>(tousLesEtudiants);

                        SwingUtilities.invokeLater(() -> {
//                            remplirToutesLesComobox();
                            // Rafraichir tous les affichages
                            rafraichirTousLesAffichages();

                            // Mettre a jour les combobox
                            remplirComboboxApresModification();

                            dialog.dispose();
                            JOptionPane.showMessageDialog(dialog, "Étudiant ajouté avec succès !", 
                                "Succès", JOptionPane.INFORMATION_MESSAGE);
                        });
                    }
                } catch (Exception ex) {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(dialog, "Erreur lors de l'ajout de l'etudiant: " + ex.getMessage(),
                            "Erreur", JOptionPane.ERROR_MESSAGE);
                    });
                }
            }).start();
        });

        btnAnnuler.addActionListener(e -> dialog.dispose());

        dialog.setVisible(true);
    }
    
    /**
    * Modifier l'étudiant sélectionné
    */
    private void modifierEtudiant() {
        int selectedRow = tblEtudiants.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un étudiant !", 
                "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        Etudiant etudiant = etudiantsFiltres.get(selectedRow);

        // Dialogue de modification
        JDialog dialog = new JDialog(this, " Modifier l'étudiant", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(400, 250);
        dialog.setLocationRelativeTo(this);

        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        formPanel.add(new JLabel("N° Étudiant :"));
        JTextField txtNe = new JTextField(etudiant.getNe());
        txtNe.setEnabled(false); // Le numéro ne se modifie pas
        formPanel.add(txtNe);

        formPanel.add(new JLabel("Nom :"));
        JTextField txtNom = new JTextField(etudiant.getNom());
        formPanel.add(txtNom);

        formPanel.add(new JLabel("Niveau :"));
        JComboBox<String> cmbNiveau = new JComboBox<>(new String[]{"L1", "L2", "L3", "M1", "M2"});
        cmbNiveau.setSelectedItem(etudiant.getNiveau());
        formPanel.add(cmbNiveau);

        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnOk = new JButton("Enregistrer");
        JButton btnAnnuler = new JButton("Annuler");
        buttonPanel.add(btnOk);
        buttonPanel.add(btnAnnuler);

        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        btnOk.addActionListener(e -> {
            String nom = txtNom.getText().trim();
            String niveau = (String) cmbNiveau.getSelectedItem();

            if (nom.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Le nom ne peut pas être vide !", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Désactiver le bouton pour éviter double clic
            btnOk.setEnabled(false);
            btnOk.setText("Envoi en cours...");

            new Thread(() -> {
                try {
                    Etudiant etudiantModifie = new Etudiant(etudiant.getNe(), nom, niveau);
                    
                    SwingUtilities.invokeLater(() -> {
                        
                    });
                    if (ApiClient.modifierEtudiant(etudiant.getNe(), etudiantModifie)) {
                        // Recharcher les donnees
                        try {
                            tousLesEtudiants = ApiClient.getEtudiants();
                            etudiantsFiltres = new ArrayList<>(tousLesEtudiants);

                            SwingUtilities.invokeLater(() -> {
                                rafraichirTousLesAffichages();
                                remplirComboboxApresModification();

                                dialog.dispose();
                                JOptionPane.showMessageDialog(dialog, "Étudiant modifié avec succès !", 
                                    "Succès", JOptionPane.INFORMATION_MESSAGE);
                            });
                        } catch (Exception ex) {
                                                       JOptionPane.showMessageDialog(MainFrame.this, 
                                "Erreur rechargement: " + ex.getMessage(),
                                "Erreur", JOptionPane.ERROR_MESSAGE); 
                        }
                        
                    } else {
                        JOptionPane.showMessageDialog(dialog, 
                            "La modification a échoué. Vérifiez le backend.",
                            "Erreur", JOptionPane.ERROR_MESSAGE);
                        btnOk.setEnabled(true);
                        btnOk.setText("Enregistrer");
                    }
                } catch (Exception ex) {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(dialog, "Erreur: " + ex.getMessage(), 
                            "Erreur", JOptionPane.ERROR_MESSAGE);
                    });  
                }
            }).start();          
        });

        btnAnnuler.addActionListener(e -> dialog.dispose());
        dialog.setVisible(true);
    }
    
    /**
    * Supprimer l'étudiant sélectionné
    */
    private void supprimerEtudiant() {
        int selectedRow = tblEtudiants.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un étudiant !", 
                "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Etudiant etudiant = etudiantsFiltres.get(selectedRow);

        int confirmation = JOptionPane.showConfirmDialog(this,
            "Supprimer l'étudiant " + etudiant.getNom() + " ?\n" +
            "Ses notes seront également supprimées.",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
//            tousLesEtudiants.remove(etudiant);
            new Thread(() -> {
                try {
                    if (ApiClient.supprimerEtudiant(etudiant.getNe())) {
                        // Recharger les donnees
                        tousLesEtudiants = ApiClient.getEtudiants();
                        toutesLesNotes = ApiClient.getNotes();
                        etudiantsFiltres = new ArrayList<>(tousLesEtudiants);

                        SwingUtilities.invokeLater(() -> {
                            rafraichirTousLesAffichages();
                            remplirComboboxApresModification();

                            JOptionPane.showMessageDialog(this, "Étudiant supprimé avec succès !", 
                                "Succès", JOptionPane.INFORMATION_MESSAGE);
                        });
                    };
                } catch (Exception e) {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Erreur suppression etudiant: " + e.getMessage(),
                                "Erreur", JOptionPane.ERROR_MESSAGE);
                    });    
                }
            }).start();         
        }
    }
    
    /**
     * Afficher les matieres
     */
    private void afficherMatieres() {
        if (toutesLesMatieres == null) return;
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Code", "Libellé", "Coefficient"}, 0
        );
        
        for (Matiere m : toutesLesMatieres) {
            model.addRow(new Object[]{m.getCodemat(), m.getLibelle(), m.getCoef()});
        }
        
        tblMatieres.setModel(model);
//        centrerColonnesTable(tblMatieres);
        tblMatieres.setRowHeight(30);
    }
    
    /**
    * Ajouter une matière (dialogue personnalisé)
    */
    private void ajouterMatiere() {
        JDialog dialog = new JDialog(this, "Ajouter une matière", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(400, 200);
        dialog.setLocationRelativeTo(this);
        
        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        formPanel.add(new JLabel("Code matière :"));
        JTextField txtCode = new JTextField();
        formPanel.add(txtCode);
        
        formPanel.add(new JLabel("Libellé :"));
        JTextField txtLibelle = new JTextField();
        formPanel.add(txtLibelle);
        
        formPanel.add(new JLabel("Coefficient :"));
        JSpinner spinCoef = new JSpinner(new SpinnerNumberModel(1, 1, 10, 1));
        formPanel.add(spinCoef);
        
//        txtCode.setColumns(20);
//        txtLibelle.setColumns(20);
//        spinCoef.setSize(75, 25);
        
        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnOk = new JButton("Enregistrer");
        JButton btnAnnuler = new JButton("Annuler");
        buttonPanel.add(btnOk);
        buttonPanel.add(btnAnnuler);
        
        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        
        btnOk.addActionListener(e -> {
            String code = txtCode.getText().trim().toUpperCase();
            String libelle = txtLibelle.getText().trim();
            int coef = (int) spinCoef.getValue();

            if (code.isEmpty() || libelle.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Veuillez remplir tous les champs !", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean existe = toutesLesMatieres.stream().anyMatch(m -> m.getCodemat().equals(code));
            if (existe) {
                JOptionPane.showMessageDialog(dialog, "Ce code matière existe déjà !", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                Matiere matiere = new Matiere(code, libelle, coef);
                
                if (ApiClient.ajouterMatiere(matiere)) {
                    toutesLesMatieres = ApiClient.getMatieres();
                    afficherMatieres();
                    dialog.dispose();
                    
                    JOptionPane.showMessageDialog(dialog, "Matière ajoutée avec succès !", 
                    "Succès", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Erreur ajout de matiere: " + ex.getMessage(),
                        "Erreur", JOptionPane.ERROR_MESSAGE);
            }

        });

        btnAnnuler.addActionListener(e -> dialog.dispose());
        dialog.setVisible(true);
    }
    
    /**
    * Modifier la matiere sélectionné
    */
    private void modifierMatiere() {
        int selectedRow = tblMatieres.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une matière !",
                        "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String code = (String) tblMatieres.getValueAt(selectedRow, 0);
        String libelleActuel = (String) tblMatieres.getValueAt(selectedRow, 1);
        int coefActuel = (int) tblMatieres.getValueAt(selectedRow, 2);
        
        JDialog dialog = new JDialog(this, "Modifier la matière", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(400, 200);
        dialog.setLocationRelativeTo(this);
        
        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        formPanel.add(new JLabel("Code matière :"));
        JTextField txtCode = new JTextField(code);
        txtCode.setEnabled(false);
        formPanel.add(txtCode);

        formPanel.add(new JLabel("Libellé :"));
        JTextField txtLibelle = new JTextField(libelleActuel);
        formPanel.add(txtLibelle);

        formPanel.add(new JLabel("Coefficient :"));
        JSpinner spinCoef = new JSpinner(new SpinnerNumberModel(coefActuel, 1, 10, 1));
        formPanel.add(spinCoef);
        
        txtCode.setColumns(20);
        txtLibelle.setColumns(20);
        spinCoef.setSize(75, 25);
        
        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnOk = new JButton("Enregistrer");
        JButton btnAnnuler = new JButton("Annuler");
        buttonPanel.add(btnOk);
        buttonPanel.add(btnAnnuler);
        
        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        btnOk.addActionListener(e -> {
            String libelle = txtLibelle.getText().trim();
            int coef = (int) spinCoef.getValue();

            if (libelle.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Le libellé ne peut pas être vide !", 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                Matiere matiere = new Matiere(code, libelle, coef);
                
                if (ApiClient.modifierMatiere(code, matiere)) {
                    toutesLesMatieres = ApiClient.getMatieres();
                    toutesLesNotes = ApiClient.getNotes();
                    afficherMatieres();
//                    chargerNotes();
                    afficherNotesFiltrees();
                    afficherBulletin();
                    afficherClassement();
                    dialog.dispose();
                    
                    JOptionPane.showMessageDialog(dialog, "Matière modifiée avec succès !", 
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Erreur Modification matiere: " + ex.getMessage(),
                        "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        });

        btnAnnuler.addActionListener(e -> dialog.dispose());
        dialog.setVisible(true);
    }
    
    /**
    * Supprimer la matiere sélectionné
    */
    private void supprimerMatiere() {
        int selectedRow = tblMatieres.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une matière !", 
                "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String code = (String) tblMatieres.getValueAt(selectedRow, 0);
        String libelle = (String) tblMatieres.getValueAt(selectedRow, 1);
        
        int confirmation = JOptionPane.showConfirmDialog(this,
            "Supprimer la matière " + libelle + " ?\n" +
            "Les notes associées seront également supprimées.",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
            try {
                if (ApiClient.supprimerMatiere(code)) {
                    toutesLesMatieres = ApiClient.getMatieres();
                    toutesLesNotes = ApiClient.getNotes();
                    afficherMatieres();
//                    chargerNotes();
                    afficherNotesFiltrees();
                    afficherBulletin();
                    afficherClassement();
                    
                    JOptionPane.showMessageDialog(this, "Matière supprimée avec succès !", 
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur suppression matiere: " + e.getMessage(),
                        "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
    * Ajouter une note
    */
    private void ajouterNote() {
        if (tousLesEtudiants.isEmpty() || toutesLesMatieres.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Veuillez d'abord ajouter des étudiants et des matières !",
                    "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JDialog dialog = new JDialog(this, "Ajouter une note", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(450, 250);
        dialog.setLocationRelativeTo(this);
        
        JPanel formPanel = new JPanel(new GridLayout(3, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        // Selection de l'Etudiant
        formPanel.add(new JLabel("Étudiant :"));
        JComboBox<String> cmbEtudiantDialog = new JComboBox<>();
        for (Etudiant e : tousLesEtudiants) {
            cmbEtudiantDialog.addItem(e.getNe() + " - " + e.getNom());
        }
        formPanel.add(cmbEtudiantDialog);
        
        // Selection de la matiere
        formPanel.add(new JLabel("Matière :"));
        JComboBox<String> cmbMatiere = new JComboBox<>();
        for (Matiere m : toutesLesMatieres) {
            cmbMatiere.addItem(m.getCodemat() + " - " + m.getLibelle());
        }
        formPanel.add(cmbMatiere);
        
        // Note
        formPanel.add(new JLabel("Note (0-20) :"));
        JSpinner spinNote = new JSpinner(new SpinnerNumberModel(10.0, 0.0, 20.0, 0.5));
        formPanel.add(spinNote);
        
        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnOk = new JButton("Enregistrer");
        JButton btnAnnuler = new JButton("Annuler");
        buttonPanel.add(btnOk);
        buttonPanel.add(btnAnnuler);
        
        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        
        btnOk.addActionListener(e -> {
            String selectedEtudiant = (String) cmbEtudiantDialog.getSelectedItem();
            String selectedMatiere = (String) cmbMatiere.getSelectedItem();
            double noteValue = (double) spinNote.getValue();
            
            String ne = selectedEtudiant.split(" - ")[0];
            String codemat = selectedMatiere.split(" - ")[0];
            
                    // Désactiver le bouton
            btnOk.setEnabled(false);
            btnOk.setText("Envoi...");
            
            new Thread(() -> {
                try {
                    Note nouvelleNote = new Note(ne, codemat, noteValue);

                    if (ApiClient.ajouterNote(nouvelleNote)) {
                        try {
                            toutesLesNotes = ApiClient.getNotes();

                            afficherNotesFiltrees();
                            afficherBulletin();
                            afficherClassement();

                            dialog.dispose();
                            JOptionPane.showMessageDialog(dialog, "Note ajoutée avec succès !", 
                                "Succès", JOptionPane.INFORMATION_MESSAGE);
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(MainFrame.this, 
                                "Erreur rechargement: " + ex.getMessage(),
                                "Erreur", JOptionPane.ERROR_MESSAGE);
                        }
                            
                    } else {
                        JOptionPane.showMessageDialog(dialog, 
                            "L'ajout a échoué. La note existe peut-être déjà.",
                            "Erreur", JOptionPane.ERROR_MESSAGE);
                        btnOk.setEnabled(true);
                        btnOk.setText("Enregistrer");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(dialog, "Erreur: " + ex.getMessage(), 
                        "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }).start();
                
        });
        
        btnAnnuler.addActionListener(e -> dialog.dispose());
        dialog.setVisible(true);
    }
    
    /**
    * Modifier la note sélectionnée
    */
    private void modifierNote() {
        int selectedRow = tblNotes.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une note !", 
                    "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Recu note selectionne
        String ne = (String) tblNotes.getValueAt(selectedRow, 0);
        String matiereLibelle = (String) tblNotes.getValueAt(selectedRow, 2);
        double noteActuelle = (double) tblNotes.getValueAt(selectedRow, 3);
        
        // TRouver le code Matiere
        Matiere matiere = toutesLesMatieres.stream()
                .filter(m -> m.getLibelle().equals(matiereLibelle))
                .findFirst()
                .orElse(null);
        
        if (matiere == null) return;
        
        // Dialog de modification 
        JDialog dialog = new JDialog(this, "Modifier la note", true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(400, 150);
        dialog.setLocationRelativeTo(this);
        
        JPanel formPanel = new JPanel(new GridLayout(1, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        formPanel.add(new JLabel("Nouvelle note (0-20) :"));
        JSpinner spinNote = new JSpinner(new SpinnerNumberModel(noteActuelle, 0.0, 20.0, 0.5));
        formPanel.add(spinNote);

        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton btnOk = new JButton("Enregistrer");
        JButton btnAnnuler = new JButton("Annuler");
        buttonPanel.add(btnOk);
        buttonPanel.add(btnAnnuler);

        dialog.add(formPanel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        btnOk.addActionListener(e -> {
            double nouvelleNote = (double) spinNote.getValue();
            
            btnOk.setEnabled(false);
            btnOk.setText("Modification...");
        
            try {
                if (ApiClient.modifierNote(ne, matiere.getCodemat(), nouvelleNote)) {
                    toutesLesNotes = ApiClient.getNotes();
                    afficherNotesFiltrees();
                    afficherBulletin();
                    afficherClassement();
                    
                    dialog.dispose();
                    JOptionPane.showMessageDialog(dialog, "Note modifiée avec succès !", 
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                            
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Erreur: " + ex.getMessage(), 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        });

        btnAnnuler.addActionListener(e -> dialog.dispose());
        dialog.setVisible(true);
    }
    
    /**
    * Supprimer la note sélectionnée
    */
    private void supprimerNote() {
        int selectedRow = tblNotes.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une note !", 
                "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String ne = (String) tblNotes.getValueAt(selectedRow, 0);
        String matiereLibelle = (String) tblNotes.getValueAt(selectedRow, 2);
        
        Matiere matiere = toutesLesMatieres.stream()
                .filter(m -> m.getLibelle().equals(matiereLibelle))
                .findFirst()
                .orElse(null);
        
        if (matiere == null) return;
        
        int confirmation = JOptionPane.showConfirmDialog(this, "Supprimer cette note ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
        
         if (confirmation == JOptionPane.YES_OPTION) {
             try {
                 if (ApiClient.supprimerNote(ne, matiere.getCodemat())) {
                     toutesLesNotes = ApiClient.getNotes();
                    
                    afficherNotesFiltrees(); 
//                    chargerNotes();
                    afficherBulletin();
                    afficherClassement();
                    
                    JOptionPane.showMessageDialog(this, "Note supprimée avec succès !", 
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                 }
             } catch (Exception ex) {
                 JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage(), 
                    "Erreur", JOptionPane.ERROR_MESSAGE);
             }   
        }
    }
    
    /**
    * Centrer le texte dans toutes les colonnes d'une JTable
    */
   private void centrerColonnesTable(JTable table) {
       DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
       centerRenderer.setHorizontalAlignment(JLabel.CENTER);
       for (int i = 0; i < table.getColumnCount(); i++) {
           table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
       }
   }
   
   /**
    * Met a jour les combobox apres une modification des donnees
    */
   private void remplirComboboxApresModification() {
       // Sauvegrader la selection actuelle pour la restaurer si possible
       String selectedEtudiant = cmbEtudiant.getSelectedItem() != null ?
               cmbEtudiant.getSelectedItem().toString() : null;
       
       String selectedFiltre = cmbFiltreNotesEtudiant.getSelectedItem() != null ?
               cmbFiltreNotesEtudiant.getSelectedItem().toString() : null;
       
       // Voder et remplir la combo du bulletin
       cmbEtudiant.removeAll();
       for (Etudiant e : tousLesEtudiants) {
           cmbEtudiant.addItem(e.getNe() + " - " + e.getNom());
       }
       
       // Restaurer la sekection du flitre notes
       cmbFiltreNotesEtudiant.removeAllItems();
       cmbFiltreNotesEtudiant.addItem("Tous les étudiants");
       for (Etudiant e : tousLesEtudiants) {
           cmbFiltreNotesEtudiant.addItem(e.getNe() + " - " + e.getNom());
       }
       
       // Restaurer la selection si possible
       if (selectedEtudiant != null) {
           cmbEtudiant.setSelectedItem(selectedEtudiant);
       }
       if (selectedFiltre != null && cmbFiltreNotesEtudiant.getItemCount() > 0) {
           cmbFiltreNotesEtudiant.setSelectedItem(selectedFiltre);
       }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterEtudiant;
    private javax.swing.JButton btnAjouterMatiere;
    private javax.swing.JButton btnAjouterNote;
    private javax.swing.JButton btnFiltrerNotes;
    private javax.swing.JButton btnModifierEtudiant;
    private javax.swing.JButton btnModifierMatiere;
    private javax.swing.JButton btnModifierNote;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnResetRecherche;
    private javax.swing.JButton btnSupprimerEtudiant;
    private javax.swing.JButton btnSupprimerMatiere;
    private javax.swing.JButton btnSupprimerNote;
    private javax.swing.JComboBox<String> cmbEtudiant;
    private javax.swing.JComboBox<String> cmbFiltreNiveau;
    private javax.swing.JComboBox<String> cmbFiltreNotesEtudiant;
    private javax.swing.JComboBox<String> cmbNiveauClassement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMoyenne;
    private javax.swing.JLabel lblObservation;
    private javax.swing.JPanel pnlBoutons;
    private javax.swing.JPanel pnlBoutonsMatieres;
    private javax.swing.JPanel pnlBulletin;
    private javax.swing.JPanel pnlClassement;
    private javax.swing.JPanel pnlEtudiants;
    private javax.swing.JPanel pnlFiltreNotes;
    private javax.swing.JPanel pnlMatieres;
    private javax.swing.JPanel pnlNotes;
    private javax.swing.JPanel pnlRecherche;
    private javax.swing.JTable tblBulletin;
    private javax.swing.JTable tblClassement;
    private javax.swing.JTable tblEtudiants;
    private javax.swing.JTable tblMatieres;
    private javax.swing.JTable tblNotes;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
